//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

let R = _R(bundle: Bundle.module)

struct _R {
  let bundle: Foundation.Bundle
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }

  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func validate() throws {

  }

  /// This `_R.color` struct is generated, and contains static references to 3 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `BgColor`.
    var bgColor: ColorResource {
      .init(name: "BgColor", path: [], bundle: bundle)
    }

    /// Color `PrimaryColor`.
    var primaryColor: ColorResource {
      .init(name: "PrimaryColor", path: [], bundle: bundle)
    }

    /// Color `TitleTextColor`.
    var titleTextColor: ColorResource {
      .init(name: "TitleTextColor", path: [], bundle: bundle)
    }
  }

  /// This `_R.image` struct is generated, and contains static references to 4 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `apple`.
    var apple: ImageResource {
      .init(
        name: "apple", path: [], bundle: bundle, locale: nil,
        onDemandResourceTags: nil)
    }

    /// Image `fork_icon`.
    var fork_icon: ImageResource {
      .init(
        name: "fork_icon", path: [], bundle: bundle, locale: nil,
        onDemandResourceTags: nil)
    }

    /// Image `google`.
    var google: ImageResource {
      .init(
        name: "google", path: [], bundle: bundle, locale: nil,
        onDemandResourceTags: nil)
    }

    /// Image `onboard`.
    var onboard: ImageResource {
      .init(
        name: "onboard", path: [], bundle: bundle, locale: nil,
        onDemandResourceTags: nil)
    }
  }
}
